name: Test K3s, Kubernetes, and MicroK8s

on:
  workflow_dispatch:
    inputs:

jobs:
  strategy-test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        kube:
          - runtime: K3s-1.18
            version: v1.18.9+k3s1
          - runtime: K3s-1.19
            version: v1.19.4+k3s1
          - runtime: K3s-1.20
            version: 1.20/stable
        test:
          - case: end-to-end
            file: test/run-end-to-end.py
          - case: webhook
            file: test/run-webhook.py

    steps:
      - name: echo strategy
        run: |
          echo "kube-runtime: " ${{ matrix.kube.runtime }}
          echo "kube-version: " ${{ matrix.kube.version }}
          echo "test-case:    " ${{ matrix.test.case }}
          echo "test-file:    " ${{ matrix.test.file }}
